// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from 'C:/迅雷下载/umi4Example/src/.umi/plugin-access';
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales, FormattedDate, FormattedDateParts, FormattedDisplayName, FormattedHTMLMessage, FormattedList, FormattedNumber, FormattedNumberParts, FormattedPlural, FormattedRelativeTime, FormattedTime, FormattedTimeParts, IntlProvider, RawIntlProvider, SelectLang } from 'C:/迅雷下载/umi4Example/src/.umi/plugin-locale';
export { Provider, useModel } from 'C:/迅雷下载/umi4Example/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from 'C:/迅雷下载/umi4Example/src/.umi/plugin-request';
export { proxy, useSnapshot, snapshot, subscribe, subscribeKey, proxyWithComputed, proxyWithHistory, proxyWithDevtools, proxyMap, proxySet, derive, underive, useProxy, ref, watch } from 'C:/迅雷下载/umi4Example/src/.umi/plugin-valtio';
// plugins types.d.ts
export * from 'C:/迅雷下载/umi4Example/src/.umi/plugin-access/types.d';
export * from 'C:/迅雷下载/umi4Example/src/.umi/plugin-antd/types.d';
export * from 'C:/迅雷下载/umi4Example/src/.umi/plugin-layout/types.d';
export * from 'C:/迅雷下载/umi4Example/src/.umi/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'C:/迅雷下载/umi4Example/node_modules/.pnpm/@umijs+renderer-react@4.3.28_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from 'C:/迅雷下载/umi4Example/node_modules/.pnpm/@umijs+renderer-react@4.3.28_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'C:/迅雷下载/umi4Example/node_modules/.pnpm/umi@4.3.28_@babel+core@7.26.0_@types+node@22.8.6_@types+react@18.3.12_eslint@8.35.0_lightning_lfgwdnmqtgbjuk2mum3n5ksb3q/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
