var json_ua=null,form_tk=document.getElementsByName("rds_form_token")[0]&&document.getElementsByName("rds_form_token")[0].value||"";"undefined"==typeof alipay&&(alipay={});alipay.auth||(alipay.auth={});alipay.auth.checkcode=function(a){this.init();for(var b in a)this[b]=a[b];if(this.form)if(this.supportAliedit()){this.bind();this.self=this}else this.showCheckCode()};
alipay.auth.checkcode.prototype={form:null,authServer:"http://authcenter.alipay.net",logonId:null,codeCnt_:null,authcode:null,uaMaxLength:1800,uaMinLength:1600,sendCode:0,formSubmit_:null,formToken:null,isPerson:!1,timeout:3E3,insertFormToken:function(){var a=this.formToken;if(!a){a=document.createElement("input");a.setAttribute("type","hidden");a.name="rds_form_token";a.value=form_tk;this.form.appendChild(a)}},supportAliedit:function(){return document.getElementsByName("J_aliedit_using")[0]&&document.getElementsByName("J_aliedit_using")[0].value===
"true"},submitAspect:function(){var a=this.form.submit,b=this;this.form.submit=function(){b.insertFormToken();b.onSubmit&&b.onSubmit.call(b);b.formSubmit_=a;if(b.sendCode==2)try{a()}catch(k){a.call(b.form)}else b.send.call(b,true)}},sendSeed:function(a){typeof Tracker!="undefined"&&Tracker.click(a)},showCheckCode:function(){this.codeCnt_.style.display="block";this.sendSeed("authlogin-showCheckCode-"+window.location.hostname.split(".")[0])},hideCheckCode:function(){this.codeCnt_.style.display="none"},
successCallback:function(a){if(a.isPerson=="true"){this.isPerson=true;this.sendSeed("authlogin-request-time-"+((new Date).getTime()-this.lastTime));if(this.formSubmit_)try{this.formSubmit_()}catch(b){this.formSubmit_.call(this.form)}}else{this.showCheckCode();this.onFailCallback&&this.onFailCallback.call(this,a)}this.sendCode=2},send:function(a){try{if(!this.sendCode){this.lastTime=(new Date).getTime();this.request(a)}}catch(b){this.failCallback()}},failCallback:function(){this.showCheckCode();this.sendCode=
2;this.onFailCallback&&this.onFailCallback.call(this,null)},jsonUaExceed:function(){this.sendSeed("authlogin-jsonUa-exceed-"+window.location.hostname.split(".")[0])}};
(function(a){if(a){var b=function(a,b,f){for(var c=0,e=a.length;c<e;c++)b.call(f||null,a[c])},k=function(h,d){b(h,function(b){var h=a[b];a[b]=function(){d(h,arguments)}})},l={callbacks:{},publish:function(a,d){this.callbacks[a]&&b(this.callbacks[a],function(a){a.apply(null,d)})},subscibe:function(a,b){this.callbacks[a]||(this.callbacks[a]=[]);this.callbacks[a].push(b)}};a.register=function(b){var d=false,f=araleConfig.combo_host.indexOf(".assets.alipay.net")!=-1?"-SNAPSHOT-index.js":"-index.js";k(["use",
"waituse"],function(b,c){d?b.apply(a,c):l.subscibe("Loader/register/use",function(){b.apply(a,c)})});for(var c=araleConfig.combo_host+araleConfig.combo_path,e=[],m=b.length,j=0;j<m;j++){var g=b[j];araleConfig.combo_path.indexOf("ar")==-1&&(g.indexOf("alipay")!=-1||g.indexOf("arale")!=-1)?e.push("/static/"+g):e.push(g)}c=c+e.join(f+",");a.loadScriptByUrl(c+f,function(){d=true;l.publish("Loader/register/use",[])})}}})(Loader);
var checkcodeExtend_={init:function(){this.form=$("login")&&$("login").node;this.logonId=$("logonId");this.authcode=$$(".sl-checkcode input[name=checkCode]");this.codeCnt_=$$(".sl-checkcode")[0].node;this.formToken=$$("input[name=rds_form_token]",$(this.form))[0]},bind:function(){var a=this;this.submitAspect();a.form&&E.connect($(a.form),"onclick",a,function(b){b=b.target;b.id=="safeSignCheck"&&(b.checked?a.isPerson&&a.hideCheckCode():a.failCallback.call(a))});if(!a.logonId||!a.logonId.node.id||!a.codeCnt_||
a.codeCnt_&&a.codeCnt_.style.display=="block")a.failCallback.call(a);else{E.connect(a.logonId,"onblur",function(){a.isLogonIdFocus&&a.send(true)});setTimeout(function(){try{(a.isLogonIdFocus=true)&&a.logonId.node.focus()}catch(b){a.failCallback.call(a)}},300);E.connect(a.logonId,"onkeyup",a,function(){a.send()})}},request:function(a){if(json_ua&&json_ua.length>=this.uaMaxLength){this.failCallback();this.jsonUaExceed()}else if(!json_ua||!(json_ua.length<this.uaMinLength)||a){this.sendCode=1;var b=
this;Loader.use("arale.http",function(){var a=b.authServer.indexOf("/login")!=-1?b.authServer:b.authServer+"/login";Ajax.jsonp(a+"/checkRds.json",{success:function(a){b.successCallback.call(b,a)},timeout:b.timeout,failure:function(){b.failCallback.call(b)},data:{action:"check",_json_token:form_tk,json_ua:json_ua,sceneCode:"AC1",stamp:(new Date).getTime()}})})}}},i;for(i in checkcodeExtend_)alipay.auth.checkcode.prototype[i]=checkcodeExtend_[i];