// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export {
  proxy,
  useSnapshot,
  snapshot,
  subscribe,
  subscribeKey,
  proxyWithComputed,
  proxyWithHistory,
  proxyWithDevtools,
  proxyMap,
  proxySet,
  derive,
  underive,
  useProxy,
  ref,
  watch,
} from 'C:/迅雷下载/umi4Example/node_modules/.pnpm/@umijs+valtio@1.0.4_@types+react@18.3.12_react@18.3.1/node_modules/@umijs/valtio';
