// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Volumes/Tools/工作区0/01/Demo00/umi4Example/src/models/counterModel';
import model_2 from '/Volumes/Tools/工作区0/01/Demo00/umi4Example/src/models/global';
import model_3 from '/Volumes/Tools/工作区0/01/Demo00/umi4Example/src/pages/CSSworld/CSS/DecorationSkip/model';
import model_4 from '/Volumes/Tools/工作区0/01/Demo00/umi4Example/src/.umi/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'counterModel', model: model_1 },
model_2: { namespace: 'global', model: model_2 },
model_3: { namespace: 'CSSworld.CSS.DecorationSkip.model', model: model_3 },
model_4: { namespace: '@@initialState', model: model_4 },
} as const
