// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/home","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"首页","path":"/home","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"权限演示","path":"/access","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":" CRUD 示例","path":"/table","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/alayout","layout":false,"id":"5"},"6":{"path":"child1","exact":true,"parentId":"5","id":"6"},"7":{"path":"/CSSworld/CSS/decorationSkip","parentId":"ant-design-pro-layout","id":"7"},"8":{"path":"/CSSworld/CSS/colorLevel4","parentId":"ant-design-pro-layout","id":"8"},"9":{"path":"/CSSworld/CSS/widthExpand","parentId":"ant-design-pro-layout","id":"9"},"10":{"path":"/CSSworld/CSS/timeline","parentId":"ant-design-pro-layout","id":"10"},"11":{"path":"/CSSworld/CSS/containerQuery","parentId":"ant-design-pro-layout","id":"11"},"12":{"path":"/CSSworld/CSS/3DHoverEffect","parentId":"ant-design-pro-layout","id":"12"},"13":{"path":"/CSSworld/JavaScript/GroupBy/:id","parentId":"ant-design-pro-layout","id":"13"},"14":{"path":"/UmiExample/valtio","parentId":"ant-design-pro-layout","id":"14"},"15":{"path":"/UmiExample/counterActions","parentId":"ant-design-pro-layout","id":"15"},"16":{"path":"/UmiExample/internationalization","parentId":"ant-design-pro-layout","id":"16"},"17":{"path":"/HookExample/useMemo","parentId":"ant-design-pro-layout","id":"17"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Access__index" */'@/pages/Access/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Table__index" */'@/pages/Table/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "layouts__a-layout" */'@/layouts/a-layout.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__a__buss1__index" */'@/pages/a/buss1/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__CSSworld__CSS__DecorationSkip__index" */'@/pages/CSSworld/CSS/DecorationSkip/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__CSSworld__CSS__ColorLevel4__index" */'@/pages/CSSworld/CSS/ColorLevel4/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__CSSworld__CSS__WidthExpand__index" */'@/pages/CSSworld/CSS/WidthExpand/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__CSSworld__CSS__Timeline__index" */'@/pages/CSSworld/CSS/Timeline/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__CSSworld__CSS__ContainerQuery__index" */'@/pages/CSSworld/CSS/ContainerQuery/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__CSSworld__CSS__3DHoverEffect__index" */'@/pages/CSSworld/CSS/3DHoverEffect/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__CSSworld__JavaScript__GroupBy__index" */'@/pages/CSSworld/JavaScript/GroupBy/index.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__UmiExample__Valtio__index" */'@/pages/UmiExample/Valtio/index.tsx')),
'15': React.lazy(() => import(/* webpackChunkName: "p__UmiExample__CounterActions__index" */'@/pages/UmiExample/CounterActions/index.tsx')),
'16': React.lazy(() => import(/* webpackChunkName: "p__UmiExample__Internationalization__index" */'@/pages/UmiExample/Internationalization/index.tsx')),
'17': React.lazy(() => import(/* webpackChunkName: "p__HookExample__UseMemo__index" */'@/pages/HookExample/UseMemo/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Volumes/Tools/工作区0/01/Demo00/umi4Example/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
